-- =============================================================================
-- SEED EXAMPLE: Project E22 → Drawing E22-111
--   Panel MDB1 (qty=1)  → sheets ELE A01–A20
--   Panel DB   (qty=10) → sheets ELE B01–B03
-- =============================================================================

-- Standards
INSERT INTO standards (id, name, region) VALUES
  ('iec', 'IEC 60617', 'IEC'),
  ('ansi', 'ANSI Y32.2', 'ANSI');

INSERT INTO busbar_standards (id, name, edition, region, standard_type) VALUES
  ('din_43671',    'DIN 43671 — Busbar Dimensions',       NULL,  'DIN', 'dimension'),
  ('din_en_61439', 'DIN EN 61439-1 — Switchgear Assemblies','2020','DIN', 'rating'),
  ('iec_61439',    'IEC 61439-1',                         '2020','IEC', 'rating'),
  ('ansi_c37_20',  'ANSI C37.20',                         NULL,  'ANSI','rating');

INSERT INTO busbar_materials (id, name, density_kg_m3) VALUES
  ('cu', 'Copper',    8900),
  ('al', 'Aluminum',  2700);

INSERT INTO busbar_sizes (id, width_mm, thickness_mm, cross_section_mm2, label, din_43671_code, is_din_standard) VALUES
  ('sz-50x5',   50,  5, 250,  '50×5',   '50x5',   TRUE),
  ('sz-50x10',  50, 10, 500,  '50×10',  '50x10',  TRUE),
  ('sz-100x10', 100,10,1000,  '100×10', '100x10', TRUE);

INSERT INTO busbar_ratings (id, standard_id, material_id, size_id, bars_per_phase, rated_current_a, temp_rise_k, icw_ka) VALUES
  ('br-db-main',  'din_en_61439','cu','sz-50x5',  1,  630, 65, 25),
  ('br-mdb-main', 'din_en_61439','cu','sz-100x10',2, 2500, 65, 50),
  ('br-mdb-f1',   'din_en_61439','cu','sz-50x10', 1,  800, 65, 36);

-- Category
INSERT INTO equipment_categories (id, code, name) VALUES
  ('cat-contactor', 'CONTACTOR', 'Contactors'),
  ('cat-mccb',      'MCCB',      'Molded Case Circuit Breakers');

-- Project
INSERT INTO projects (id, name, code, customer, symbol_standard, busbar_rating_standard, busbar_dimension_standard)
VALUES ('proj-e22', 'E22 Factory', 'E22', 'ABC Ltd', 'iec', 'din_en_61439', 'din_43671');

-- Drawing E22-111
INSERT INTO drawings (id, project_id, drawing_no, title, revision, status)
VALUES ('drw-e22-111', 'proj-e22', 'E22-111', 'Electrical Panel Drawing Set', 'A', 'released');

-- Panel Designs
INSERT INTO panel_designs (id, drawing_id, panel_code, name, production_qty, sheet_prefix, sort_order) VALUES
  ('panel-mdb1', 'drw-e22-111', 'MDB1', 'Main Distribution Board', 1,  'A', 1),
  ('panel-db',   'drw-e22-111', 'DB',   'Distribution Board',      10, 'B', 2);

-- Panel Instances (DB × 10)
INSERT INTO panel_instances (id, panel_design_id, instance_no, serial_no, asset_tag) VALUES
  ('pi-mdb1',    'panel-mdb1', 1, 'E22-111-MDB1-001', 'MDB1');
-- (DB-01 … DB-10 generated by app; example 2 rows:)
INSERT INTO panel_instances (id, panel_design_id, instance_no, serial_no, asset_tag) VALUES
  ('pi-db-01', 'panel-db', 1,  'E22-111-DB-001', 'DB-01'),
  ('pi-db-02', 'panel-db', 2,  'E22-111-DB-002', 'DB-02');

-- Sheets (sample — full set A01-A20, B01-B03 created by app)
INSERT INTO panel_sheets (id, panel_design_id, sheet_no, display_name, title, sort_order) VALUES
  ('sh-a01', 'panel-mdb1', 'A01', 'ELE A01', 'Single Line Diagram',  1),
  ('sh-a02', 'panel-mdb1', 'A02', 'ELE A02', 'Power Circuit',        2),
  ('sh-b01', 'panel-db',   'B01', 'ELE B01', 'Single Line Diagram',  1),
  ('sh-b02', 'panel-db',   'B02', 'ELE B02', 'Power & Control',      2);

-- Busbar config MDB1
INSERT INTO panel_busbar_configs (id, panel_design_id, rating_standard_id, dimension_standard_id, material_id)
VALUES ('bbc-mdb1', 'panel-mdb1', 'din_en_61439', 'din_43671', 'cu');

INSERT INTO panel_busbar_sections (id, config_id, section_role, feeder_tag, rating_id, bars_per_phase, length_mm, sort_order) VALUES
  ('bbs-mdb-main', 'bbc-mdb1', 'main',     NULL, 'br-mdb-main', 2, 2400, 1),
  ('bbs-mdb-f1',   'bbc-mdb1', 'feeder',   'F1', 'br-mdb-f1',   1,  600, 2);

-- Busbar config DB
INSERT INTO panel_busbar_configs (id, panel_design_id, rating_standard_id, dimension_standard_id, material_id)
VALUES ('bbc-db', 'panel-db', 'din_en_61439', 'din_43671', 'cu');

INSERT INTO panel_busbar_sections (id, config_id, section_role, rating_id, bars_per_phase, length_mm, sort_order) VALUES
  ('bbs-db-main', 'bbc-db', 'main', 'br-db-main', 1, 800, 1);

-- Production Order
INSERT INTO production_orders (id, project_id, drawing_id, order_no, status)
VALUES ('po-001', 'proj-e22', 'drw-e22-111', 'PO-E22-0088', 'open');

INSERT INTO production_order_lines (id, order_id, panel_design_id, quantity) VALUES
  ('pol-1', 'po-001', 'panel-mdb1', 1),
  ('pol-2', 'po-001', 'panel-db',   10);

UPDATE panel_sheets SET sheet_type = 'single_line', schematic_status = 'in_progress'
WHERE id IN ('sh-a01', 'sh-b01');

UPDATE panel_sheets SET sheet_type = 'power' WHERE id = 'sh-a02';
UPDATE panel_sheets SET sheet_type = 'control' WHERE title LIKE '%Control%';
